[project]
name = "rules-pycross-test"
version = "0.1.0"
description = ""
requires-python = ">=3.9, <3.13"
dependencies = [
    "cowsay==6.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
