[tool.poetry]
name = "rules-pycross-test"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
zstandard = "0.22.0"
setuptools = ">=75.6.0"
wheel = ">=0.45.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
